models/compras.py
from utils.db import db 

class Compra(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_producto = db.Column(db.Integer, nullable=False)
    proveedor = db.Column(db.String(80), nullable=False)
    producto = db.Column(db.String(120), nullable=False)
    precio_unitario = db.Column(db.Float, nullable=False)
    cantidad = db.Column(db.Integer, nullable=False)
    fecha = db.Column(db.String(50), nullable=False)
    total_compra = db.Column(db.Float, nullable=False)
    
    def __init__(self, id_producto, proveedor, producto, precio_unitario, cantidad, fecha=None, total_compra=0, ) -> None:
        self.id_producto = id_producto
        self.proveedor = proveedor
        self.producto = producto
        self.precio_unitario = precio_unitario
        self.cantidad = cantidad
        self.fecha = fecha
        self.total_compra = total_compra
        
        
    def __repr__(self):
        return f"User({self.id}, '{self.id_producto}', '{self.proveedor}', '{self.producto}', '{self.precio_unitario}', '{self.cantidad}', '{self.fecha}', '{self.total_compra}')" 

forms/comprasForm.py
from flask_wtf import FlaskForm
from wtforms import FloatField
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import InputRequired, Length



class Nueva_Compra(FlaskForm):
    proveedor = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=80),
        ],
        render_kw={"placeholder": "Proveedor"},
    )
    
    
    precio_unitario = FloatField(
        validators=[
            InputRequired(),
        ],
        render_kw={"placeholder": "Precio unitario"},
    )
    
    cantidad = IntegerField(
        validators=[
            InputRequired(),
        ],
        render_kw={"placeholder": "Cantidad de artículos"},
    )
    
    fecha = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=50),
        ],
        render_kw={"placeholder": "fecha"},
    )
    

    submit = SubmitField("agregar")

routes/compras.py
from flask import Blueprint, render_template, redirect, url_for
from models.compras import Compra
from models.inventario import Inventario
from forms.comprasForm import Nueva_Compra
from flask_login import login_required, current_user
from utils.db import db

compras = Blueprint("compras", __name__, url_prefix="/purchase")

@compras.route("/")
@login_required
def home():
    lista_compras = Compra.query.all()
    return render_template("compras/home.html", items=lista_compras, user=current_user)



@compras.route("/new/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def NuevaCompra(id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    form = Nueva_Compra()
    if form.validate_on_submit():
        id_producto = id_producto
        proveedor = form.proveedor.data
        producto = nombre_producto.producto
        precio_unitario = form.precio_unitario.data
        cantidad = form.cantidad.data
        fecha = form.fecha.data
        total_compra = precio_unitario * cantidad

        nuevaCompra = Compra(id_producto, proveedor, producto, precio_unitario, cantidad, fecha, total_compra)
        db.session.add(nuevaCompra)
        db.session.commit()
        
        nombre_producto.existencia = nombre_producto.existencia + cantidad
        db.session.commit()
        return redirect(url_for("compras.home"))
    return render_template("compras/nueva.html", form=form, user=current_user, id_producto=id_producto)


@compras.route("/delete/<int:id>/<int:id_producto>")
@login_required
def EliminarCompra(id, id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    delete_compra = Compra.query.get(id)
    nombre_producto.existencia = nombre_producto.existencia - delete_compra.cantidad
    db.session.delete(delete_compra)
    db.session.commit()
    db.session.commit()
    return redirect(url_for("compras.home"))


@compras.route("/update/<int:id>", methods=['GET', 'POST'])
@login_required
def ActualizarCompra(id):
    compra_actual = Compra.query.get(id)
    form = Nueva_Compra()
    if form.validate_on_submit():
        compra_actual.id_producto = compra_actual.id_producto
        compra_actual.proveedor = form.proveedor.data
        compra_actual.producto = compra_actual.producto
        compra_actual.precio_unitario = form.precio_unitario.data
        compra_actual.cantidad = form.cantidad.data
        compra_actual.fecha = form.fecha.data
        compra_actual.total_compra = compra_actual.precio_unitario * compra_actual.cantidad
        db.session.commit()
        return redirect(url_for("compras.home"))
    return render_template("compras/actualizar.html", form=form, item=compra_actual, user=current_user, id=id)

templates/compras/actualizar.html
{% extends '/compras/base.html' %}

{% block title %}Actualizar Compra{% endblock  %}

{% block contents %}
<br>
<h3>Los detalles de la compra actualmenete son:</h3>
<br>
<br>
{% if item %}
<ul>
        <li>Id: {{ item.id }}</li>
        <li>Id del producto: {{ item.id_producto }}</li>
        <li>Proveedor: {{ item.proveedor }}</li>
        <li>Producto: {{ item.producto }}</li>
        <li>Precio por unidad: {{ item.precio_unitario }}</li>
        <li>Cantidad comprada: {{ item.cantidad }}</li>
        <li>Fecha de compra: {{ item.fecha }}</li>
        <li>Total: {{ item.total_compra }}</li>
</ul>
{% endif %}

<h1>Cambio en la compra</h1>
<br>
<br>
<h3>Por favor ingrese la información actualizada de la compra</h3>
<br>
<br>
{% if user %}
<form action="{{ url_for('compras.ActualizarCompra', id=id) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.proveedor.label }}
    {{ form.proveedor }}
    {{ form.precio_unitario.label }}
    {{ form.precio_unitario }}
    {{ form.cantidad.label }}
    {{ form.cantidad }}
    {{ form.fecha.label }}
    {{ form.fecha }}
    {{ form.submit }}

</form>
{% endif %}

{% endblock  %}

templates/compras/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
</head>
<body>
    <h1>Página de compras</h1>
    <br>    
    {% block contents %}{% endblock  %}

</body>
</html>

templates/compras/home.html
{% extends '/compras/base.html' %}

{% block title %}Compras{% endblock  %}

{% block contents %}
<br>
{% if user %}
<p>Bienvenido, {{user.username}}</p>
{% endif %}
<br>
<br>
<table>
    <thead>
        <tr>
            <th> Id </th>
            <th> Id producto </th>
            <th> Proveedor </th>
            <th> Producto </th>
            <th> Precio unitario </th>
            <th> Cantidad </th>
            <th> Fecha de compra </th>
            <th> Total </th>
        </tr>
    </thead>
    
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.id_producto }}</td>
            <td>{{ item.proveedor }}</td>
            <td>{{ item.producto }}</td>
            <td>{{ item.precio_unitario }}</td>
            <td>{{ item.cantidad }}</td>
            <td>{{ item.fecha }}</td>
            <td>{{ item.total_compra }}</td>
            <td><a href="{{ url_for('compras.EliminarCompra', id=item.id, id_producto = item.id_producto) }}">Eliminar</a></td>
            <td><a href="{{ url_for('compras.ActualizarCompra', id=item.id, id_producto=item.id_producto) }}">Actualizar </a></td>
        </tr>

        {% endfor %}
    </tbody>

</table>
<br>
<br>
<a href="{{ url_for('productos.home')}}">Ver Inventario</a>
<br>
<br>
<a href="{{ url_for('ventas.home')}}">Ver Ventas</a>

{% endblock  %}

templates/compras/nueva.html
{% extends '/compras/base.html' %}

{% block title %}Agregar Compra{% endblock  %}

{% block contents %}
<h1>Compra nueva</h1>
<br>
<h3>Por favor ingrese los detalles de la compra</h3>
{% if user %}
<br>
<br>
<form action="{{ url_for('compras.NuevaCompra', id_producto=id_producto) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.proveedor.label }}
    {{ form.proveedor }}
    {{ form.precio_unitario.label }}
    {{ form.precio_unitario }}
    {{ form.cantidad.label }}
    {{ form.cantidad }}
    {{ form.fecha.label }}
    {{ form.fecha }}
    {{ form.submit }}

</form>
{% endif %}

{% endblock  %}