models/ventas.py
from utils.db import db 

class Venta(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    id_producto = db.Column(db.Integer, nullable=False)
    cliente = db.Column(db.String(80), nullable=True)
    producto = db.Column(db.String(120), nullable=False)
    precio_unitario = db.Column(db.Float, nullable=False)
    cantidad = db.Column(db.Integer, nullable=False)
    fecha = db.Column(db.String(50), nullable=False)
    total_venta = db.Column(db.Float, nullable=False)
    
    def __init__(self, id_producto, cliente, producto, precio_unitario, cantidad, fecha=None, total_venta=0, ) -> None:
        self.id_producto = id_producto
        self.cliente = cliente
        self.producto = producto
        self.precio_unitario = precio_unitario
        self.cantidad = cantidad
        self.fecha = fecha
        self.total_venta = total_venta
        
        
    def __repr__(self):
        return f"User({self.id}, '{self.id_producto}', '{self.cliente}', '{self.producto}', '{self.precio_unitario}', '{self.cantidad}', '{self.fecha}', '{self.total_venta}')" 

forms/ventasForm.py
from flask_wtf import FlaskForm
from wtforms import FloatField
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import InputRequired, Length



class Nueva_Venta(FlaskForm):
    cliente = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=80),
        ],
        render_kw={"placeholder": "Nombre del cliente"},
    )
    
    
    precio_unitario = FloatField(
        validators=[
            InputRequired(),
        ],
        render_kw={"placeholder": "Precio unitario de venta"},
    )
    
    cantidad = IntegerField(
        validators=[
            InputRequired(),
        ],
        render_kw={"placeholder": "Cantidad comprada"},
    )
    
    fecha = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=50),
        ],
        render_kw={"placeholder": "dd/mm/aa"},
    )
    

    submit = SubmitField("agregar")

routes/ventas.py
from flask import Blueprint, render_template, redirect, url_for
from models.ventas import Venta
from models.inventario import Inventario
from forms.ventasForm import Nueva_Venta
from flask_login import login_required, current_user
from utils.db import db

ventas = Blueprint("ventas", __name__, url_prefix="/sales")

@ventas.route("/")
@login_required
def home():
    lista_ventas = Venta.query.all()
    return render_template("ventas/home.html", items=lista_ventas, user=current_user)



@ventas.route("/new_sale/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def NuevaVenta(id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    form = Nueva_Venta()
    if form.validate_on_submit():
        id_producto = id_producto
        cliente = form.cliente.data
        producto = nombre_producto.producto
        precio_unitario = form.precio_unitario.data
        cantidad = form.cantidad.data
        fecha = form.fecha.data
        total_venta = precio_unitario * cantidad

        nuevaVenta = Venta(id_producto, cliente, producto, precio_unitario, cantidad, fecha, total_venta)
        db.session.add(nuevaVenta)
        db.session.commit()
        
        nombre_producto.existencia = nombre_producto.existencia - cantidad
        db.session.commit()
        return redirect(url_for("ventas.home"))
    return render_template("ventas/nuevo.html", form=form, user=current_user, id_producto=id_producto)


@ventas.route("/delete_sale/<int:id>/<int:id_producto>")
@login_required
def EliminarVenta(id, id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    delete_venta = Venta.query.get(id)
    nombre_producto.existencia = nombre_producto.existencia + delete_venta.cantidad
    db.session.delete(delete_venta)
    db.session.commit()
    db.session.commit()
    return redirect(url_for("ventas.home"))

@ventas.route("/update/<int:id>/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def ActualizarVenta(id, id_producto):
    existencia_actual = Inventario.query.get(id_producto)
    venta_actual = Venta.query.get(id)
    form = Nueva_Venta()
    if form.validate_on_submit():
        venta_actual.id_producto = venta_actual.id_producto
        venta_actual.cliente = form.cliente.data
        venta_actual.producto = venta_actual.producto
        venta_actual.precio_unitario = form.precio_unitario.data
        venta_actual.cantidad = form.cantidad.data
        venta_actual.fecha = form.fecha.data
        venta_actual.total_venta = venta_actual.precio_unitario * venta_actual.cantidad
        existencia_actual.existencia = existencia_actual.existencia + venta_actual.cantidad
        db.session.commit()
        db.session.commit()
        return redirect(url_for("ventas.home"))
    return render_template("ventas/actualizar.html", form=form, item=venta_actual, user=current_user, id=id, id_producto=id_producto)

templates/ventas/actualizar.html
{% extends '/ventas/base.html' %}

{% block title %}Actualizar Venta{% endblock  %}

{% block contents %}
<br>
<h3>Los detalles de la venta actualmenete son:</h3>
<br>
<br>
{% if item %}
<ul>
        <li>Id: {{ item.id }}</li>
        <li>Id del producto: {{ item.id_producto }}</li>
        <li>Cliente: {{ item.cliente }}</li>
        <li>Producto: {{ item.producto }}</li>
        <li>Precio por unidad: {{ item.precio_unitario }}</li>
        <li>Cantidad comprada: {{ item.cantidad }}</li>
        <li>Fecha de venta: {{ item.fecha }}</li>
        <li>Total: {{ item.total_venta }}</li>
</ul>
{% endif %}

<h1>Cambio en la venta</h1>
<br>
<br>
<h3>Por favor ingrese la información actualizada de la venta</h3>
<br>
<br>
{% if user %}
<form action="{{ url_for('ventas.ActualizarVenta', id=id, id_producto = id_producto) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.cliente.label }}
    {{ form.cliente }}
    {{ form.precio_unitario.label }}
    {{ form.precio_unitario }}
    {{ form.cantidad.label }}
    {{ form.cantidad }}
    {{ form.fecha.label }}
    {{ form.fecha }}
    {{ form.submit }}

</form>
{% endif %}

{% endblock  %}

templates/ventas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
</head>
<body>
    <h1>Página de ventas</h1>
    <br>    
    {% block contents %}{% endblock  %}

</body>
</html>

templates/ventas/home.html
{% extends '/ventas/base.html' %}

{% block title %}Ventas{% endblock  %}

{% block contents %}
<br>
{% if user %}
<p>Bienvenido, {{user.username}}</p>
{% endif %}
<br>
<br>
<table>
    <thead>
        <tr>
            <th> Id </th>
            <th> Id producto </th>
            <th> Cliente </th>
            <th> Producto </th>
            <th> Precio unitario de venta </th>
            <th> Cantidad vendida </th>
            <th> Fecha de venta </th>
            <th> Total </th>
        </tr>
    </thead>
    
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.id_producto }}</td>
            <td>{{ item.cliente }}</td>
            <td>{{ item.producto }}</td>
            <td>{{ item.precio_unitario }}</td>
            <td>{{ item.cantidad }}</td>
            <td>{{ item.fecha }}</td>
            <td>{{ item.total_venta }}</td>
            <td><a href="{{ url_for('ventas.EliminarVenta', id=item.id, id_producto =item.id_producto) }}">Eliminar</a></td>
            <td><a href="{{ url_for('ventas.ActualizarVenta', id=item.id, id_producto =item.id_producto) }}">Actualizar </a></td>
        </tr>

        {% endfor %}
    </tbody>

</table>
<br>
<br>
<a href="{{ url_for('productos.home')}}">Inventario</a>
<br>
<br>
<a href="{{ url_for('compras.home')}}">Ver Compras</a>

{% endblock  %}

templates/ventas/nuevo.html
{% extends '/compras/base.html' %}

{% block title %}Agregar Venta{% endblock  %}

{% block contents %}
<h1>Venta nueva</h1>
<br>
<h3>Por favor ingrese los detalles de la venta</h3>
{% if user %}
<br>
<br>
<form action="{{ url_for('ventas.NuevaVenta', id_producto=id_producto) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.cliente.label }}
    {{ form.cliente }}
    {{ form.precio_unitario.label }}
    {{ form.precio_unitario }}
    {{ form.cantidad.label }}
    {{ form.cantidad }}
    {{ form.fecha.label }}
    {{ form.fecha }}
    {{ form.submit }}

</form>
{% endif %}

{% endblock  %}