forms/loginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class LoginForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("login")

forms/registerForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class RegisterForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("register")

    def validate_username(self, username):
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            raise ValidationError("the username already exists")

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    return render_template("home.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("productos.home"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

templates/dashboard.html
{% extends 'layout.html' %}
{% block title %}Dashboard{% endblock %}
{% block contents %}

{% if user %}
<h1>Página de control de inventario</h1>
<br>
<br>
<h4>Bienvenido, {{user.username}}</h4>
<br>
<br>
<a href="{{ url_for('compras.home') }}">COMPRAS</a>
<br>
<a href="#">VENTAS</a>
{% endif %}
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}Detalles de la empresa{% endblock %}
{% block contents %}
<h1>Inventario</h1>
<br>
<a href="{{ url_for('auth.login') }}">login</a><br>
<a href="{{ url_for('auth.register') }}">register</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block contents %}{% endblock %}
</body>

</html>

templates/login.html
{% extends 'layout.html' %}
{% block title %}login page{% endblock %}
{% block contents %}
<h1>login page</h1>
<br>
<form action="{{ url_for('auth.login') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.register') }}">register</a>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% block title %}register page{% endblock %}
{% block contents %}
<h1>register page</h1>
<br>
<form action="{{ url_for('auth.register') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.login') }}">login</a>
{% endblock %}