models/inventario.py
from utils.db import db 

class Inventario(db.Model):
    id_producto = db.Column(db.Integer, primary_key=True)
    producto = db.Column(db.String(120), nullable=False)
    existencia = db.Column(db.Integer, nullable=False)


    
    def __init__(self, producto, existencia) -> None:
        self.producto = producto
        self.existencia = existencia
      
        
    def __repr__(self):
        return f"User({self.id_producto}, '{self.producto}', '{self.existencia}')" 

forms/inventarioForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import InputRequired, Length



class Nuevo_Producto(FlaskForm):
    producto = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=120),
        ],
        render_kw={"placeholder": "Producto"},
    )
    
    existencia = IntegerField(
        validators=[
            InputRequired(),
        ],
        render_kw={"placeholder": "Cantidad en existencia"},
    )


    submit = SubmitField("agregar")

routes/compras.py
from flask import Blueprint, render_template, redirect, url_for
from models.compras import Compra
from models.inventario import Inventario
from forms.comprasForm import Nueva_Compra
from flask_login import login_required, current_user
from utils.db import db

compras = Blueprint("compras", __name__, url_prefix="/purchase")

@compras.route("/")
@login_required
def home():
    lista_compras = Compra.query.all()
    return render_template("compras/home.html", items=lista_compras, user=current_user)



@compras.route("/new/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def NuevaCompra(id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    form = Nueva_Compra()
    if form.validate_on_submit():
        id_producto = id_producto
        proveedor = form.proveedor.data
        producto = nombre_producto.producto
        precio_unitario = form.precio_unitario.data
        cantidad = form.cantidad.data
        fecha = form.fecha.data
        total_compra = precio_unitario * cantidad

        nuevaCompra = Compra(id_producto, proveedor, producto, precio_unitario, cantidad, fecha, total_compra)
        db.session.add(nuevaCompra)
        db.session.commit()
        
        nombre_producto.existencia = nombre_producto.existencia + cantidad
        db.session.commit()
        return redirect(url_for("compras.home"))
    return render_template("compras/nueva.html", form=form, user=current_user, id_producto=id_producto)


@compras.route("/delete/<int:id>/<int:id_producto>")
@login_required
def EliminarCompra(id, id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    delete_compra = Compra.query.get(id)
    nombre_producto.existencia = nombre_producto.existencia - delete_compra.cantidad
    db.session.delete(delete_compra)
    db.session.commit()
    db.session.commit()
    return redirect(url_for("compras.home"))


@compras.route("/update/<int:id>", methods=['GET', 'POST'])
@login_required
def ActualizarCompra(id):
    compra_actual = Compra.query.get(id)
    form = Nueva_Compra()
    if form.validate_on_submit():
        compra_actual.id_producto = compra_actual.id_producto
        compra_actual.proveedor = form.proveedor.data
        compra_actual.producto = compra_actual.producto
        compra_actual.precio_unitario = form.precio_unitario.data
        compra_actual.cantidad = form.cantidad.data
        compra_actual.fecha = form.fecha.data
        compra_actual.total_compra = compra_actual.precio_unitario * compra_actual.cantidad
        db.session.commit()
        return redirect(url_for("compras.home"))
    return render_template("compras/actualizar.html", form=form, item=compra_actual, user=current_user, id=id)

routes/inventario.py
from flask import Blueprint, render_template, redirect, url_for
from models.inventario import Inventario  
from models.compras import Compra
from models.ventas import Venta
from forms.inventarioForm import Nuevo_Producto
from flask_login import login_required, current_user
from utils.db import db

productos = Blueprint("productos", __name__, url_prefix="/products")

@productos.route("/")
@login_required
def home():
    lista_productos = Inventario.query.all()
    return render_template("inventario/home.html", items=lista_productos, user=current_user)

@productos.route("/new_product", methods=['GET', 'POST'])
@login_required
def NuevoProducto():
    form = Nuevo_Producto()
    if form.validate_on_submit():
        producto = form.producto.data
        existencia = form.existencia.data

        nuevoProducto = Inventario(producto, existencia)
        db.session.add(nuevoProducto)
        db.session.commit()
        return redirect(url_for("productos.home"))
    return render_template("inventario/nuevo.html", form=form, user=current_user)


@productos.route("/delete_product/<int:id_producto>")
@login_required
def EliminarProducto(id_producto):
    delete_producto = Inventario.query.get(id_producto)
    delete_compra = Compra.query.filter_by(id_producto = id_producto).all()
    delete_venta = Venta.query.filter_by(id_producto = id_producto).all()
    db.session.delete(delete_producto)
    for item in delete_compra:
        db.session.delete(item)
        db.session.commit()
    for item in delete_venta:
        db.session.delete(delete_venta)
        db.session.commit()
    
    db.session.commit()
    return redirect(url_for("productos.home"))

routes/ventas.py
from flask import Blueprint, render_template, redirect, url_for
from models.ventas import Venta
from models.inventario import Inventario
from forms.ventasForm import Nueva_Venta
from flask_login import login_required, current_user
from utils.db import db

ventas = Blueprint("ventas", __name__, url_prefix="/sales")

@ventas.route("/")
@login_required
def home():
    lista_ventas = Venta.query.all()
    return render_template("ventas/home.html", items=lista_ventas, user=current_user)



@ventas.route("/new_sale/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def NuevaVenta(id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    form = Nueva_Venta()
    if form.validate_on_submit():
        id_producto = id_producto
        cliente = form.cliente.data
        producto = nombre_producto.producto
        precio_unitario = form.precio_unitario.data
        cantidad = form.cantidad.data
        fecha = form.fecha.data
        total_venta = precio_unitario * cantidad

        nuevaVenta = Venta(id_producto, cliente, producto, precio_unitario, cantidad, fecha, total_venta)
        db.session.add(nuevaVenta)
        db.session.commit()
        
        nombre_producto.existencia = nombre_producto.existencia - cantidad
        db.session.commit()
        return redirect(url_for("ventas.home"))
    return render_template("ventas/nuevo.html", form=form, user=current_user, id_producto=id_producto)


@ventas.route("/delete_sale/<int:id>/<int:id_producto>")
@login_required
def EliminarVenta(id, id_producto):
    nombre_producto = Inventario.query.get(id_producto)
    delete_venta = Venta.query.get(id)
    nombre_producto.existencia = nombre_producto.existencia + delete_venta.cantidad
    db.session.delete(delete_venta)
    db.session.commit()
    db.session.commit()
    return redirect(url_for("ventas.home"))

@ventas.route("/update/<int:id>/<int:id_producto>", methods=['GET', 'POST'])
@login_required
def ActualizarVenta(id, id_producto):
    existencia_actual = Inventario.query.get(id_producto)
    venta_actual = Venta.query.get(id)
    form = Nueva_Venta()
    if form.validate_on_submit():
        venta_actual.id_producto = venta_actual.id_producto
        venta_actual.cliente = form.cliente.data
        venta_actual.producto = venta_actual.producto
        venta_actual.precio_unitario = form.precio_unitario.data
        venta_actual.cantidad = form.cantidad.data
        venta_actual.fecha = form.fecha.data
        venta_actual.total_venta = venta_actual.precio_unitario * venta_actual.cantidad
        existencia_actual.existencia = existencia_actual.existencia + venta_actual.cantidad
        db.session.commit()
        db.session.commit()
        return redirect(url_for("ventas.home"))
    return render_template("ventas/actualizar.html", form=form, item=venta_actual, user=current_user, id=id, id_producto=id_producto)

templates/inventario/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
</head>
<body>
    <h1>Página de inventario</h1>
    <br>    
    {% block contents %}{% endblock  %}

</body>
</html>

templates/inventario/home.html
{% extends '/inventario/base.html' %}

{% block title %}Inventario{% endblock  %}

{% block contents %}
<br>
{% if user %}
<p>Bienvenido, {{user.username}}</p>
{% endif %}
<br>
<br>
<a href="{{ url_for('productos.NuevoProducto') }}">Agregar producto</a>
<br>
<br>
<table>
    <thead>
        <tr>
            <th> Id producto </th>
            <th> Producto </th>
            <th> Existencia </th>
        </tr>
    </thead>
    
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id_producto }}</td>
            <td>{{ item.producto }}</td>
            <td>{{ item.existencia }}</td>
            <td><a href="{{ url_for('productos.EliminarProducto', id_producto = item.id_producto) }}"> Eliminar </a></td>
            <td><a href="{{ url_for('compras.NuevaCompra', id_producto = item.id_producto) }}"> Compra </a></td>
            <td><a href="{{ url_for('ventas.NuevaVenta', id_producto = item.id_producto) }}"> Venta </a></td>
        </tr>
        
        {% endfor %}
    </tbody>

</table>
<br>
<br>
<a href="{{ url_for('compras.home') }}"> Ver Compras </a>
<br>
<br>
<a href="{{ url_for('ventas.home') }}"> Ver Ventas </a>
{% endblock  %}

templates/inventario/nuevo.html
{% extends '/compras/base.html' %}

{% block title %}Agregar Producto{% endblock  %}

{% block contents %}
<h1>Producto nuevo</h1>
<br>
<h3>Por favor ingrese los detalles del Producto</h3>
{% if user %}
<br>
<br>
<form action="{{ url_for('productos.NuevoProducto') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.producto.label }}
    {{ form.producto }}
    {{ form.existencia.label }}
    {{ form.existencia }}
    {{ form.submit }}

</form>
{% endif %}

{% endblock  %}